[package]
name = "blanks"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
clap = { version = "4.4.11", features = ["derive"] }
colored = "2.0.4"
ctrlc = "3.4.1"
rand_chacha = "0.3.1"
chrono = "0.4.31"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
